# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.

ifeq ($(CONFIG_E404_OPLUS),y)
obj-$(CONFIG_OPLUS_OPROJECT) 	+= oplus_project.o oemports10t.o
obj-$(CONFIG_OPLUS_NANDSWAP)	+= nandswap_core.o
obj-$(CONFIG_OPLUS_WAKELOCK_PROFILER)	+= oplus_wakelock_profiler.o
obj-$(CONFIG_OPLUS_SUBSYS_SLEEP_MONITOR)	+= oplus_subsys_sleep_monitor.o
obj-$(CONFIG_OPLUS_NWPOWER) += oplus_nwpower.o oplus_ipv6_rto.o
endif
