name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison build-essential ccache curl flex g++-multilib gcc-multilib \
            git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev \
            lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev \
            libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools \
            xsltproc zip zlib1g-dev python3

      - name: Setup Clang
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

      - name: Setup ReSukiSU
        run: |
          rm -rf KernelSU KernelSU-Next drivers/kernelsu
          curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash

      - name: Configure
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          make O=out ARCH=arm64 vendor/alioth_defconfig

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export PATH="${{ github.workspace }}/clang/bin:$PATH"

          make -j$(nproc --all) O=out \
          ARCH=arm64 \
          CC=clang \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=aarch64-linux-android- \
          CROSS_COMPILE_ARM32=arm-linux-androideabi-

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: out/arch/arm64/boot/Image.gz-dtb
